language: go # 声明构建语言环境
sudo: false # 开启基于容器的Travis CI任务，让编译效率更高。

notifications: # 每次构建的时候是否通知，如果不想收到通知，那就设置false吧(email: false,也可以是Slack)
  # slack: xxxx:xxxxxxxxxx
  email:
    recipients:
      - 15989067460@163.com
  on_success: change
  on_failure: always

go:
  - 1.11

install: #依赖安装
  - go get github.com/99designs/gqlgen
  - go get github.com/go-playground/overalls  #overalls能够支持到各级子目录
  - go get github.com/mattn/goveralls         #goveralls是coveralls对golang的测试覆盖率支持命令
  - go get github.com/smartystreets/goconvey  #很好用的测试工具

script: # 集成脚本
  - go build
  - go test -v ./test/... -covermode=count -coverprofile=coverage.out -coverpkg="github.com/Go-GraphQL-Group/GraphQL-Service/..."
  - $GOPATH/bin/goveralls -v -coverprofile=coverage.out -service=travis-ci
  # - $GOPATH/bin/overalls -project=github.com/Go-GraphQL-Group/GraphQL-Service -covermode=count -ignore='.git,_vendor'
  # - $GOPATH/bin/goveralls -coverprofile=overalls.coverprofile -service=travis-ci -repotoken $COVERALLS_TOKEN
  # - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

# env:  #env环境变量设置，travis提供的repo_token安全方式
#   global:
#     secure: "xxxx"