language: go # 声明构建语言环境
sudo: false # 开启基于容器的Travis CI任务，让编译效率更高。

notifications: # 每次构建的时候是否通知，如果不想收到通知，那就设置false吧(email: false,也可以是Slack)
  # slack: xxxx:xxxxxxxxxx
  email:
    recipients:
      - 15989067460@163.com
  on_success: change
  on_failure: always

go:
  - 1.11

install: #依赖安装
  - go get github.com/go-playground/overalls  #overalls能够支持到各级子目录
  - go get github.com/mattn/goveralls         #goveralls是coveralls对golang的测试覆盖率支持命令
  - go get github.com/smartystreets/goconvey  #很好用的测试工具
  - mkdir -p $GOPATH/src/github.com/Go-GraphQL-Group
  - cd $GOPATH/src/github.com/Go-GraphQL-Group/GraphQL-Service

script: # 集成脚本
  - overalls -project=github.com/Go-GraphQL-Group/GraphQL-Service -covermode=count -ignore='.git,_vendor'
  - goveralls -coverprofile=coverage.out -service=travis-ci
  - go test ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

# env:  #env环境变量设置，travis提供的repo_token安全方式
#   global:
#     secure: "xxxx"