version: "3.3"
services:
  database:
    image: liuyh73/starwars_db:latest
    container_name: starwars_db
    restart: always
    ports: 
      - "3306:3306"
    # volumes: 
    #   - data:/mysql
    # environment:
    #   MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    #   MYSQL_DATABASE: starwars
    #   MYSQL_USER: starwars
    #   MYSQL_PASSWORD_FILE: /run/secrets/db_user_password
    # secrets:
    #   - db_root_password
    #   - db_user_password
  server:
    depends_on:
      - database
    image: liuyh73/starwars_server:latest
    container_name: starwars_server
    restart: always
    ports: 
      - "9090:9090"
    external_links:
      - starwars_db:starwars_db
  client:
    depends_on:
      - database
      - server
    image: liuyh73/starwars_client:latest
    container_name: starwars_client
    restart: always
    ports:
      - "80:80"
    external_links:
      - starwars_server:starwars_server
# secrets:
#   db_user_password:
#     file: conf/db_user_password.txt
#   db_root_password:
#     file: conf/db_root_password.txt

# volumes:
#   data:
